name: Streamlink to Telegram RTMP with Watermark

on:
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Streamlink and FFmpeg
      - name: Set up Streamlink and FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg streamlink

      # Step 2: Start Streaming with Watermark
      - name: Start Streaming with Watermark
        env:
          INPUT_URL: ${{ secrets.INPUT_URL }}
          RTMP_URL: ${{ secrets.RTMP_URL }}
          REFERER_HEADER: ${{ secrets.REFERER_HEADER }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          ORIGIN_HEADER: ${{ secrets.ORIGIN_HEADER }}
        run: |
          streamlink \
          --http-header "Referer=$REFERER_HEADER" \
          --http-header "User-Agent=$USER_AGENT" \
          --http-header "Origin=$ORIGIN_HEADER" \
          "$INPUT_URL" best --stdout | \
          ffmpeg -re -i - \
          -vf "drawtext=text='TipiStream':fontcolor=white:fontsize=24:x=180:y=180" \
          -c:v libx264 -preset veryfast -c:a aac -b:a 64k -f flv "$RTMP_URL"
